name: freecompose
description: freecompose
version: 0.0.1+0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: "^3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  intapp:
    path: ../../../int/impl/frontend
  boolapp:
    path: ../../../bool/impl/frontend

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
