version=0.1
[default.global.parameters]
stack_name = "collection-api"

[default.deploy.parameters]
s3_bucket = "jackson-concepts-templates"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_prefix = "collection-api"
image_repositories = []
