name: boolapp
description: bool app
version: 0.0.1+0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: "^3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.1.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  logging: ^1.0.2
  boolgen:
    path: packages/boolgen/generated/bool

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
