AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Contributing Factor Resources

Globals:
  Function:
    Timeout: 40

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: v1
      DefinitionUri: Functions/src/main/resources/api.yaml

  ContributingFactorCategory:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: contributing_factor_category
        CodeUri: Functions
        Handler: edu.uva.cs.concepts.lambda.concrete.S3CategoryHandler::handleRequest
        Runtime: java8.al2
        Architectures:
          - x86_64
        MemorySize: 512
        Environment:
          Variables:
            bucket: jackson-concepts-concepts
            key: contributing-factor/category.json
        Role: !Sub arn:aws:iam::${AWS::AccountId}:role/contributing_factor_category_lambda_role
Outputs:
  APIUri:
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com"
