template: 
  type: file
  path: managed_policy_attachable_role.template
parameters:
  Name: contributing_factor_category_agw_role
  ManagedPolicyArns:
    - !stack_output category/iam/policies/agw/policy.yaml::PolicyArn
  Services:
    - apigateway.amazonaws.com
