# Copyright © 2001 by the Rectors and Visitors of the University of Virginia. 

# User moralpain_config as a base image until this project diverges enough
# to justify its own Dockerfile from scratch.
FROM ghcr.io/kevinsullivan/moralpain_config:sha-ad23dae