template:
  path: iam_managed_policy.j2
  type: file

sceptre_user_data:
  PolicyDocument: !file config/collection/iam/policies/lambda/policy.json

parameters:
  Name: collection_collection_lambda_policy
