name: int
version: 0.0.1
description: An integer object.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  openapi_generator_annotations: ^4.0.0

dev_dependencies:
  build_runner:
  openapi_generator: ^4.0.0
