openapi: "3.0.1"
info:
  title: Integer
  description: Integer object
  version: 1.0.0
paths: {}
components:
  schemas:
    Int:
      type: object
      properties:
        value:
          type: integer
