template:
  path: iam_managed_policy.j2
  type: file

sceptre_user_data:
  PolicyDocument: !file config/description/iam/policies/agw/policy.json

parameters:
  Name: contributng_factor_description_agw_policy
